### ISSUE TITLE
Composition Documentation and Behaviour

### ISSUE THREAD

**Issue by robjacoby** [apotonick/disposable#1]
Currently, there is no documentation for compositions in the Readme, however looking in the source code, we see that Compositions should be defined as follows

```ruby
class Album
  include Disposable::Composition

  map( {cd: [[:id], [:name]], band: [[:id, :band_id], [:title]]} )
end
```

The current version of the Trailblazer book however, alludes to being able to define Compositions like this

```ruby
class Comment::Opinion < Disposable::Twin
  include Composition
  
  property :body,  on: :comment
  property :email, on: :author 
end
```

Which I feel is a much nicer DSL

Is the latter the plan for how compositions will work?

**Comment by apotonick** [comment]
Absolutely, and I am currently working on Disposable. I will make it all very nice, darling! Thanks for pointing that out. :heart: 

Are you following this repo or do you want me to keep you in the loop?
