### ISSUE TITLE
Save needs Sync, but doesn't automatically include it

### ISSUE THREAD

**Issue by krainboltgreene** [apotonick/disposable#23]
This causes methods to not be found, kinda annoying.

**Comment by apotonick** [comment]
Then, why isn't this a straight PR, my friend? :stuck_out_tongue_winking_eye:

**Comment by krainboltgreene** [comment]
Well because I'm not sure save should depend on sync. I looked through the source and couldn't find a compelling reason.

**Comment by apotonick** [comment]
Good point. Well, until today, everyone thinks of twin's `save` as "sync, then save the persisted model". Does that make sense?

**Comment by krainboltgreene** [comment]
Interesting. So as we see in #24 they aren't entirely the pair-able, as nested collections *sometimes* have writers.

For what it's worth I love the `#sync` terminology and idea, and on further consideration I do think it should be `sync` -> `save`, but I'm not sure it should be implicit.

**Comment by apotonick** [comment]
The problem is ActiveRecord, as you pointed out: `sync` sometimes saves implicitly, but I documented that. Not sure why we would provide a save without a sync... where would that be helpful???

**Comment by krainboltgreene** [comment]
@apotonick Some twins don't need syncing, like my collection twin.

**Comment by apotonick** [comment]
Semantically, they do need syncing, but this just doesn't work with ActiveRecord (or am I wrong here?).

With a clean ORM, you'd create an arbitrary collection in the cart twin, sync all twin item properties to the item models, and then sync the collection to the model with the association. In ActiveRecord, this will implicitly save, but that's the wrong behaviour.

So, technically, twin is doing it right and you "need" syncing on a collection!

**Comment by krainboltgreene** [comment]
> Semantically, they do need syncing, but this just doesn't work with ActiveRecord (or am I wrong here?).

Yes, we can say with relative safety that all good data stores have the utility of defining reducers, which is the foundation for filters. Filters have no "sync". Their items may be synced and saved, but a filter collection has no concept of being "stored".

**Comment by apotonick** [comment]
We're talking about two different things: You mean read-only collections for presentation, I see a twin as a CRUD domain object that gives you the API your domain needs and not the API that database tables dictate.

So, what about this?

```ruby
collection :items, writeable: false # items is scope method!
```

**Comment by krainboltgreene** [comment]
@apotonick The problem with that example is that last time I tried it (I try things a lot before bothering with an issue) it made all of the subsequent times not eligable for writing. If I could say: `writeable: { nested: true, root: false }` or something...
