### ISSUE TITLE
Order collection

### ISSUE THREAD

**Issue by TheSmartnik** [apotonick/disposable#25]
Hi Nick,
I wonder whether it is possible or not to somehow order collection. Something like:
```ruby
class AlbumTwin < Disposable::Twin
  collection :songs, order: [:by_duration, :by_created] do
    property :name
    property :duration
  end
end

class Album < ActiveRecord::Base
  scope :by_duration, -> { order(by_duration: :asc) }
  scope :by_created, -> { order(by_created: :desc) }
end
```

Well, I mean, I know that it is not in current API right now, but maybe I could somehow implement desired behavior?

**Comment by Tab10id** [comment]
Haha! I think about it today too=) But it's not about only order. In scope we can do any strange things
```Ruby
scope :active, -> { where(active: true) }
```
or
```Ruby
scope :strange_scope, { Thing.where() }
```
It's all about mapping

**Comment by TheSmartnik** [comment]
Oh, right. Support for scopes would be even better. Although, I'm afraid it may lead to some unexpected behavior in case of `strange_scope`

**Comment by apotonick** [comment]
This already works!!! :smile: You simply have to name your collection after the scope.

```ruby
class AlbumTwin < Disposable::Twin
  collection :by_duration { .. }
```

Twins are not ORM mappers, they are data mappers that simply wrap arbitrary objects and collections into predictable in-memory objects.

Also, this is a duplicate with https://github.com/apotonick/disposable/issues/22.
