### ISSUE TITLE
Relationship keys

### ISSUE THREAD

**Issue by krainboltgreene** [apotonick/disposable#26]
Even if just as an alias it would be nice.

``` ruby
class CartTwin < ...
  relationship :items
end
```

I know you want to be agnostic, but we're still talking about wrapping models and most models I've seen (mongoid, activemodel, activerecord, etc) have relationships.

**Comment by apotonick** [comment]
Instead of `Twin::collection`?

**Comment by krainboltgreene** [comment]
As an `alias` by default, but with that opens up the doorway to easily and knowingly defining special behavior for relationships in gems that extend `disposable` (hint: I'm doing this).

**Comment by apotonick** [comment]
Hm... should we place that into `Disposable::Twin::ORM` (that's how we structure that in Reform), and then go from there? Once we need ActiveRecord tests, we should go with `disposable-activerecord`. Or `disposable-orm` as scopes and all the other things you suggest are not really AR-specific, are they?
