### ISSUE TITLE
No self.model_name for twin

### ISSUE THREAD

**Issue by krainboltgreene** [apotonick/disposable#27]
Something expects `self.model_name`, which is kinda annoying to handle.

It'd be really awesome if I could, as a feature, dump in `ActiveModel` or `ActiveRecord` assumptions (`table_name` is another).

**Comment by apotonick** [comment]
Yeah I know, this is ActiveRecord bullshit. Where do you need `table_name`?

**Comment by krainboltgreene** [comment]
@apotonick It's due to some serializer situations. We managed to flub it for now. How about tonight I'll drop my hacks into these issues so you can evaluate them?

**Comment by apotonick** [comment]
Yo're not usin' https://github.com/apotonick/roar ? Your fault! :stuck_out_tongue_winking_eye:

**Comment by apotonick** [comment]
And, man, of course, send what you got for us, then we talk! :beers:

**Comment by krainboltgreene** [comment]
Haha, I actually have never heard of roar. We're using AMS. I will definitely try it out in a side project tho. I honestly prefer to write poro objecst for that layer, I'm not a big fan of the Serializer-That-Is-Really-Presenter-Normalizer-Serializer pattern.

**Comment by apotonick** [comment]
Roar also parses documents using the same document definition.
