### ISSUE TITLE
Subclassing removes custom accessors

### ISSUE THREAD

**Issue by niels** [apotonick/disposable#36]
Upon subclassing a Twin that defines custom accessors via instance methods, they get overwritten with the stock implementation. To wit:

```ruby
class ParentTwin < Disposable::Twin
  property :my_property

  def my_property
    "auto-getter overwritten!"
  end
end

class ChildTwin < ParentTwin
end

parent_twin = ParentTwin.new(OpenStruct.new)
puts parent_twin.my_property.inspect #=> is "auto-getter overwritten!" as expected

child_twin = ChildTwin.new(OpenStruct.new)
puts child_twin.my_property.inspect #=> is nil, but should be "auto-getter overwritten"
```

I believe that this is due to the stock accessors being included through a module in https://github.com/apotonick/disposable/blob/master/lib/disposable/twin.rb#L52. As the module inclusion happens after the actual class inheritance, the module's (included) methods overwrite the parent classes (inherited) methods.

This is very counter-intuitive and makes subclassing extremely painful in cases where you want to propagate custom methods down the inheritance chain.

I would suggest either revisiting the design choice of including the getters as a module, or delegating to `super` (if present) from within the module.

Thoughts?

**Comment by niels** [comment]
Please see #37 for a proposed fix.

**Comment by niels** [comment]
Mmmh.. While this now works for simple direct inheritance, when including forms, custom accessors must be put into a module to include separately:

```ruby
module IdealIncludedForm
  include Reform::Form::Module

  property :included_property, virtual: true

  # Call me!
  def included_property
    super.to_s.upcase
  end

  # Another unloved method.
  def included_property=(val)
    super("#{val} I must've called a thousand times..")
  end
end

class BrokenForm < Reform::Form
  include IdealIncludedForm
end

form = BrokenForm.new(OpenStruct.new)
form.included_property = "Hello from the other side,"
puts form.included_property #=> Expected "HELLO FROM THE OTHER SIDE, I MUST'VE CALLED A THOUSAND TIMES" but is "Hello from the other side,"

module UnwieldyIncludedForm
  include Reform::Form::Module

  property :included_property, virtual: true

  def self.included(base)
    super

    custom_accessors = Module.new do
      def included_property
        super.to_s.upcase
      end

      def included_property=(val)
        super("#{val} I must've called a thousand times..")
      end
    end

    base.include(custom_accessors)
  end
end

class FunctioningForm < Reform::Form
  include UnwieldyIncludedForm
end
```

Is this on purpose? If so, perhaps it calls for a DSL extension to support easier accessors overrides in all circumstances:

```ruby
module InAPerfectWorld
  property :included_property, virtual: true

  accessors do
    def included_property
      super.to_s.upcase
    end

    def included_property=(val)
      super("#{val} I must've called a thousand times..")
    end
  end
end
```

I suppose we could then more easily keep track of custom accessors and where they were defined to better drive the "should default accessors be created?" logic. This would however need to be designed carefully to support inheritance. E.g. if A overrides accessors, B overrides them again calling super, and C includes A, then B, I would expect C#accessor to defer to B#accessor which in turn includes A#accessor through `super`.

Alternatively (and preferably IMO), I see that `Reform::Form::Module` already `extend`s `base` with `ClassMethods`. Perhaps we could extend that convention by also `include`ing `InstanceMethods`.

**Comment by apotonick** [comment]
Good one, thanks for finding out that nasty behaviour!

The problem is that your custom accessors are included *before* the properties are defined by Reform, and hence overwritten. I do not really know how to fix that...

**Comment by apotonick** [comment]
Now that I think about this: this problem must have existed before 2.1! Here's the flow what happens.

1. Ruby includes methods from module into form class.
2. `property` gets called on the form class.
3. `property` defines generic accessor that overrides original one.

The only solution I can think of is `accessors`, as you suggested.

**Comment by apotonick** [comment]
Hey @niels, I tried solving it with your suggestion of `InstanceMethods`.

```ruby
module SongModule
  include Reform::Form::Module

  property :id    # no custom accessor for id.
  property :title # has custom accessor.

  module InstanceMethods
    def title
      super.upcase
    end
  end
end
```

Unfortunately, that's the only clean solution without using any `append_features` hacks.

Let me know if that works for you! :beers:

**Comment by niels** [comment]
Thanks, you are a beautiful man! :beers:
