### ISSUE TITLE
Why sync no method?

### ISSUE THREAD

**Issue by chenge** [apotonick/disposable#4]
![2015-06-28 2 52 53](https://cloud.githubusercontent.com/assets/252333/8395476/8ea05bd0-1da5-11e5-80fa-0f8e6ec00fa6.png)

I really like the idea of Twin object.

**Comment by apotonick** [comment]
What a beautiful screenshot! :heart_eyes: 

You have to include `Sync`, sorry, my bad in documenting! Thanks!

**Comment by chenge** [comment]
I got it, thanks a lot. I'll continue try to play with it.
