### ISSUE TITLE
Breaking uber changes

### ISSUE THREAD

**Issue by randomizor** [apotonick/disposable#55]
Gemspec does not lock uber at or under a version number. Uber recently updated to v0.1.0 and introduced breaking changes (undefined method class_builder). Took me a little while to track down...

**Comment by apotonick** [comment]
Very good point, I pushed a new dependency to all other gems but forgot about Disposable.

**Comment by fran-worley** [comment]
This was actioned via https://github.com/apotonick/disposable/commit/ed7dda756e98d35d67cfa0f86d9008bd4d4ed133 now closing
