### ISSUE TITLE
Travis is not passing on rubies 1.9 and 2.0

### ISSUE THREAD

**Issue by abinoam** [apotonick/disposable#59]
See:
* Previous .travis.yml: https://travis-ci.org/apotonick/disposable/builds/186775154
* Updated .travis.yml: https://travis-ci.org/abinoam/disposable/builds/196008704

It's probably related to dry-rb dependency. 
Dry-rb has dropped support for old rubies.

Related to: https://github.com/trailblazer/representable/issues/208

**Comment by fran-worley** [comment]
Travis has been updated via #72
