### ISSUE TITLE
Private method exception using "parent" feature with reform on rails-4.2.x

### ISSUE THREAD

**Issue by svoop** [apotonick/disposable#61]
The following happens on the Rails console:

```ruby
require "disposable/twin/parent"
class TestForm < Reform::Form
  feature Disposable::Twin::Parent
end
# => NoMethodError: private method `property' called for TestForm:Class
```

Here's a vanilla Rails 4.2.8 app bundling "reform" and "reform-rails" (both from master) to showcase the problem:

https://github.com/svoop/disposable-issue-61

**Comment by svoop** [comment]
Here's a vanilla Rails 4.2.8 app bundling "reform" and "reform-rails" (both from master) to showcase the problem:

https://github.com/svoop/disposable-issue-61

**Comment by apotonick** [comment]
Fixed in 0.4.3.

**Comment by svoop** [comment]
Cool, thanks a bunch, @apotonick!

**Comment by apotonick** [comment]
How could this bug survive for so long??? :octopus:
