### ISSUE TITLE
Accessing properties source without lots of code

### ISSUE THREAD

**Issue by brightbits** [apotonick/disposable#7]
My code needs to know which model a property is on, after going through the source, I ended up with:

```ruby
on_model = form.class.representer_class.representable_attrs[:definitions][property_name][:on]
model = form.object.model[on_model]
```

I'd really like to just do

```ruby
form.property_definiton(property_name).model
```

or something

**Comment by apotonick** [comment]
In Reform, we got `#options_for` which boils this down to `form.options_for(:songs)[:on]`, is that maybe what you're looking for?

Not seeing a problem with moving that part to Disposable itself, too! :smile:

**Comment by brightbits** [comment]
Yeah, that is nice, could definitely move down in to disposable though. Would be great to put the hash behind a simple model also, #[] accessors look a big nasty and it'd be nice to add the helper method to directly get the model, instead of getting the model name then looking it up. I'd be happy to add this feature if you would like me to.

**Comment by apotonick** [comment]
What's ugly about the `Definition#[]` reader? I find it less ugly than `method_missing`.

**Comment by brightbits** [comment]
I'd just implement a proper class that takes the definition and exposes methods to access the standard things from it, as well as adding helpers for `method` etc. No `method_missing` madness :)

**Comment by apotonick** [comment]
Ha! You already get a proper object, a `Representable::Definition` instance and if you try to implement readers without `method_missing` you will have a busy life adding every user's special option as a reader method to your gem! :stuck_out_tongue_closed_eyes: Trust me, I have thought about that for many years and decided to go with the `#[]`, although I see your point.

I don't quite understand the "helper method that directly get the model"??

**Comment by brightbits** [comment]
ahh, ok, my bad. Quacks like a hash, but is a model.

So instead of doing 

```ruby
model_name = form.class.representer_class.representable_attrs[:definitions]["property"][:on] # or via options_for
model = form.model[model_name]
```

You'd just be able to do

```ruby
model = form.class.representer_class.representable_attrs[:definitions]["property"].model
```

Though getting it that way, we'd have no reference to the instance for which to get it, if going via options_for it'd be possible?

Sorry if I'm not making sense :)

**Comment by apotonick** [comment]
You do make sense haha. However, this is behaviour very specific to `Composition`. As this is only one of the many ways you can use a twin/form I'd rather not push that into the core lib.

You have all methods you need to grab all information you need (e.g. `model[:part]` and `#options_for`). They might be a bit clumsy, yet, but you can introduce abstracting methods in your application and make them easier to use. Then, once you know what you want and found your best practise, we can discuss that for Disposable core? Deal?

**Comment by brightbits** [comment]
Sure I understand your concern about it being specific to `Composition`. I'll tidy it up in my own code and will see what is best from there.

Feel free to close for now :)

Cheers

**Comment by apotonick** [comment]
I'll leave it open to remind you that we need your best pracises here. :beers:

**Comment by apotonick** [comment]
In Disposable 0.2, this is a simple as `Twin.definitions.get(:name_of_property)[:option]`
