### ISSUE TITLE
"Reverse" sync

### ISSUE THREAD

**Issue by ivanyv** [apotonick/disposable#70]
Would sync'ing the model to the twin be an anti-pattern? Sometimes it happens that callbacks in the model (yeah I know) would change an attribute, which is a property in the twin which in turn would now be stale.

**Comment by apotonick** [comment]
Haha, well, the canonical way would be to reinstantiate a fresh copy of your twin.

**Comment by ivanyv** [comment]
Hmm I figure, thanks!
